name: mehrab
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 2.6.0+48

environment:
  sdk: ^3.7.0


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  shared_preferences: ^2.5.2
  get_it: ^9.2.0
  dartz: ^0.10.1
  flutter_bloc: ^9.1.0
  lottie: ^3.3.1
  fluttertoast: ^9.0.0
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  carousel_slider: ^5.0.0
  intl:  ^0.20.0
  url_launcher: ^6.3.1
  path_provider: ^2.1.5
  photo_view: ^0.15.0
  file_picker: ^10.3.8
  flutter_native_splash: ^2.4.5
  permission_handler: ^12.0.1
  hexcolor: ^3.0.1
  flutter_staggered_animations: ^1.1.1
  upgrader: ^12.5.0
  device_preview: ^1.2.0
  custom_clippers: ^2.0.0
  image_picker: ^1.2.0
  image_cropper: ^11.0.0
  dropdown_button2: ^2.3.9
  mime: ^2.0.0
  audioplayers: ^6.5.1
  flutter_custom_clippers: ^2.1.0
  smooth_page_indicator: ^2.0.1
  dotted_border: ^3.1.0
  in_app_review: ^2.0.10
  flutter_local_notifications: ^19.1.0
  http: ^1.3.0
  webview_flutter: ^4.10.0
  animations: ^2.0.11
  countup: ^0.1.4
  workmanager: ^0.9.0+3
  flutter_speed_dial: ^7.0.0
  package_info_plus: ^9.0.0
  hijri: ^3.0.0
  connectivity_plus: ^7.0.0
  flutter_rating_bar: ^4.0.1
  font_awesome_flutter: ^10.4.0
  flutter_sticky_header: ^0.8.0
  local_auth: ^3.0.0
  flutter_secure_storage: ^10.0.0
  sign_in_with_apple: ^7.0.1
  open_filex: ^4.3.4
  syncfusion_flutter_pdfviewer: ^32.1.24
  # agora_rtc_engine: ^6.5.3  # Replaced by WebRTC
  flutter_webrtc: ^1.2.1
  socket_io_client: ^3.0.2
  audio_session: ^0.2.2
  proximity_sensor: ^1.3.9
  screen_off: ^1.0.0
  flutter_callkit_incoming: ^3.0.0
  uuid: ^4.5.1
  flutter_foreground_task: ^9.2.0
  device_info_plus: ^12.3.0








  #Firebase
  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4
  #firebase_database: ^11.3.10
  firebase_messaging: ^16.1.1
  cloud_firestore: ^6.1.2
  firebase_storage: ^13.0.6
  firebase_analytics: ^12.1.1
  googleapis: ^15.0.0
  googleapis_auth: ^2.0.0
  google_sign_in: ^7.2.0
  firebase_app_check: ^0.4.1+4
  intl_phone_field: ^3.2.0
  html: ^0.15.4








dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter_native_splash:
  color: "#E9F2F7"
  color_dark: "#E9F2F7"
  image: assets/images/logo.png
  image_dark: assets/images/logo.png
  ios : true
  android_12:
    #image: assets/images/android12Splash.png
    color: "#E9F2F7"
    color_dark: "#E9F2F7"
    #image_dark: assets/images/android12Splash.png

flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/fonts/
    - assets/lang/
    - assets/json/
    - assets/audio/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:



  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 500
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 900


    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Light.ttf
          weight: 400
        - asset: assets/fonts/Cairo-Regular.ttf
          weight: 500
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/Cairo-SemiBold.ttf
          weight: 500
        - asset: assets/fonts/Cairo-ExtraBold.ttf
          weight: 900


    - family: Amiri
      fonts:
        - asset: assets/fonts/AmiriQuran-Regular.ttf
          weight: 500

    - family: IconBroken
      fonts:
        - asset: assets/fonts/icons.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages